export const en = {
  common: {
    back: 'Back',
    cancel: 'Cancel',
    close: 'Close',
    retry: 'Try Again',
    loading: 'Loading',
    save: 'Save',
    saving: 'Saving…',
  },
  brand: {
    name: 'DistributorOS',
    tagline: 'Distribution management, without the clutter.',
  },
  startup: {
    loadingTitle: 'Checking your session',
    loadingMessage: 'DistributorOS is securely restoring your account.',
    errorTitle: 'We could not check your session',
    errorMessage: 'The server could not be reached. If the free server is starting, try again in a moment.',
  },
  login: {
    title: 'Welcome back',
    subtitle: 'Sign in to continue to your business.',
    emailLabel: 'Email',
    emailPlaceholder: 'owner@example.com',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Enter your password',
    action: 'Sign In',
    loading: 'Signing In…',
    noAccount: 'New to DistributorOS?',
    createAccount: 'Create an account',
    forgotPassword: 'Forgot password?',
    passwordChanged: 'Your password was changed. Sign in with your new password.',
  },
  password: {
    forgotTitle: 'Reset your password',
    forgotSubtitle: 'Enter your account email and we will send a secure reset link.',
    forgotAction: 'Send Reset Link',
    forgotLoading: 'Sending Reset Link…',
    forgotSuccess: 'If an account exists for that email, a password reset link will be sent shortly.',
    backToLogin: 'Back to sign in',
    resetTitle: 'Choose a new password',
    resetSubtitle: 'Use at least 8 characters. Completing this reset signs out existing sessions.',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    currentPassword: 'Current Password',
    resetAction: 'Reset Password',
    resetLoading: 'Resetting Password…',
    changeTitle: 'Change Password',
    changeSubtitle: 'Changing your password securely signs out every active session.',
    changeAction: 'Change Password',
    changeLoading: 'Changing Password…',
  },
  signup: {
    title: 'Create your business account',
    subtitle: 'Set up the secure foundation for your business.',
    businessNameLabel: 'Business Name',
    businessNamePlaceholder: 'Your business name',
    emailLabel: 'Email',
    emailPlaceholder: 'owner@example.com',
    passwordLabel: 'Password',
    passwordPlaceholder: 'At least 8 characters',
    action: 'Create Account',
    loading: 'Creating Account…',
    hasAccount: 'Already have an account?',
    signIn: 'Sign in',
  },
  validation: {
    businessNameRequired: 'Business name is required.',
    businessNameTooLong: 'Business name must not exceed 120 characters.',
    emailRequired: 'Email is required.',
    emailInvalid: 'Please enter a valid email.',
    passwordRequired: 'Password is required.',
    passwordTooShort: 'Password must contain at least 8 characters.',
    passwordTooLong: 'Password must not exceed 128 characters.',
    passwordsDoNotMatch: 'Passwords do not match. Enter the same password in both fields.',
    currentPasswordIncorrect: 'Current password is incorrect. Check it and try again.',
  },
  errors: {
    emailRegistered: 'This email is already registered. Sign in or use a different email.',
    invalidCredentials: 'Incorrect email or password. Check your details and try again.',
    sessionExpired: 'Your session has expired. Sign in again to continue.',
    businessAccess: 'Your account is not connected to this business. Contact support for access.',
    forbidden: 'You do not have permission to perform this action.',
    notFound: 'The requested information was not found. Refresh and try again.',
    network: 'The server could not be reached. If the free server is starting, try again in a moment.',
    server: 'The server could not complete this request. Please try again.',
    validation: 'Check the highlighted information and try again.',
    currencyChangeRestricted: 'Currency cannot be changed after financial transactions exist. Keep the current currency to preserve historical amounts.',
    rateLimited: 'Too many attempts. Wait briefly and try again.',
    passwordResetInvalid: 'This password reset link is invalid or expired. Request a new link.',
    currentPasswordIncorrect: 'Current password is incorrect. Check it and try again.',
    passwordUnchanged: 'Choose a new password that is different from your current password.',
    unknown: 'DistributorOS could not complete this action. Please try again.',
  },
  home: {
    status: 'Account ready',
    title: 'Your foundation is secure',
    subtitle: 'Authentication and business isolation are active.',
    businessLabel: 'Business',
    emailLabel: 'Signed in as',
    signOut: 'Sign Out',
    manageCustomers: 'Manage Customers',
    manageProducts: 'Manage Products',
    manageInventory: 'Manage Inventory',
    manageSales: 'Manage Sales',
    managePayments: 'Manage Payments',
    manageInvoices: 'Manage Invoices',
    businessSettings: 'Business Settings',
    quickActions: 'Quick Actions',
    modules: {
      customers: {
        title: 'Customers',
        description: 'Add and manage customer details.',
      },
      products: {
        title: 'Products',
        description: 'Manage products, units, and prices.',
      },
      inventory: {
        title: 'Inventory',
        description: 'Review stock and record movements.',
      },
      sales: {
        title: 'Sales',
        description: 'Create, review, and post sales.',
      },
      payments: {
        title: 'Payments',
        description: 'Record and track customer collections.',
      },
      invoices: {
        title: 'Invoices',
        description: 'Create and share customer invoices.',
      },
    },
  },
  navigation: {
    home: 'Home',
    sales: 'Sales',
    customers: 'Customers',
    products: 'Products',
    more: 'More',
  },
  more: {
    title: 'More',
    subtitle: 'More business tools and application settings.',
    items: {
      inventory: {
        title: 'Inventory',
        subtitle: 'Review stock balances, history, and movements.',
      },
      payments: {
        title: 'Payments',
        subtitle: 'Record collections and review payment history.',
      },
      invoices: {
        title: 'Invoices',
        subtitle: 'Create, issue, download, and share invoices.',
      },
      reports: {
        title: 'Reports',
        subtitle: 'Open read-only business reports and exports.',
      },
      search: {
        title: 'Search',
        subtitle: 'Find records across every business module.',
      },
      settings: {
        title: 'Settings',
        subtitle: 'Manage business, appearance, language, and account settings.',
      },
    },
  },
  settings: {
    open: 'Settings',
    openHint: 'Open business, appearance, language, and account settings.',
    title: 'Settings',
    subtitle: 'Manage your business and personal experience.',
    businessSection: 'Business',
    businessDescription: 'Business identity and the currency used for new records.',
    businessName: 'Business Name',
    businessNamePlaceholder: 'Your business name',
    currency: 'Currency',
    currencyHelp: 'All new financial records use this currency. Existing invoices keep their original currency.',
    timezone: 'Business Timezone',
    timezonePlaceholder: 'Asia/Kolkata',
    timezoneHelp: 'Use an IANA timezone such as Asia/Kolkata. Dates, reports, and exports use this timezone.',
    appearanceSection: 'Appearance',
    appearanceDescription: 'Choose how DistributorOS looks on this device.',
    language: 'Language',
    languageSection: 'Language',
    languageHelp: 'Language changes are applied instantly across DistributorOS.',
    english: 'English',
    malayalam: 'Malayalam',
    theme: 'Theme',
    themeHelp: 'Use a light, dark, or device-controlled appearance.',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    themeOptions: {
      light: 'Always use the light color theme.',
      dark: 'Always use the dark color theme.',
      system: 'Follow this device’s appearance setting.',
    },
    languageOptions: {
      en: 'Display DistributorOS in English.',
      ml: 'Display DistributorOS in Malayalam.',
    },
    accountSection: 'Account',
    accountDescription: 'Your signed-in identity and business membership.',
    accountEmail: 'Email',
    accountBusiness: 'Business Name',
    changePassword: 'Change Password',
    changePasswordHint: 'Update your password and sign out other sessions.',
    save: 'Save Settings',
    saving: 'Saving Settings…',
    success: 'Business settings updated successfully.',
    errorTitle: 'Settings could not be saved',
    loadError: 'Business settings could not be loaded. Check your connection and try again.',
    validation: {
      businessNameRequired: 'Business name is required.',
      businessNameTooLong: 'Business name must not exceed 120 characters.',
      timezoneRequired: 'Business timezone is required.',
      timezoneInvalid: 'Enter a valid timezone, such as Asia/Kolkata.',
    },
  },
  logout: {
    title: 'Sign out of DistributorOS?',
    message: 'Are you sure you want to sign out?',
    confirm: 'Sign Out',
    confirmAccessibilityLabel: 'Confirm Sign Out',
    loading: 'Signing Out…',
  },
  unsavedChanges: {
    title: 'Discard unsaved changes?',
    message: 'Your changes have not been saved. Discard them and leave this screen?',
    discard: 'Discard Changes',
    keepEditing: 'Keep Editing',
  },
  customers: {
    list: {
      title: 'Customers',
      subtitle: 'Manage customer contact information for this business.',
      create: 'Add Customer',
      searchLabel: 'Search customers',
      searchPlaceholder: 'Name, phone, code, or email',
      filterLabel: 'Customer status',
      sortLabel: 'Sort customers',
      loadingTitle: 'Loading customers',
      loadingMessage: 'DistributorOS is retrieving your customer list.',
      errorTitle: 'Customers could not be loaded',
      errorMessage: 'Check your connection and try loading the customer list again.',
      emptyTitle: 'No customers yet',
      emptyMessage: 'Add your first customer to begin managing customer information.',
      noResultsTitle: 'No matching customers',
      noResultsMessage: 'Try a different name, phone number, customer code, or email.',
      noArchivedTitle: 'No archived customers',
      noArchivedMessage: 'Customers you archive will appear here.',
      loadingMore: 'Loading more customers…',
      updating: 'Updating customer results…',
      archivedBadge: 'Archived',
    },
    filters: {
      all: 'All Customers',
      active: 'Active',
      archived: 'Archived',
    },
    sorts: {
      newest: 'Newest',
      oldest: 'Oldest',
      nameAsc: 'Alphabetical A–Z',
      nameDesc: 'Alphabetical Z–A',
    },
    fields: {
      name: 'Customer Name',
      customerCode: 'Customer Code',
      phone: 'Phone',
      email: 'Email',
      addressLine1: 'Address Line 1',
      addressLine2: 'Address Line 2',
      city: 'City',
      state: 'State',
      postalCode: 'Postal Code',
      notes: 'Notes',
      status: 'Status',
      createdAt: 'Created',
      updatedAt: 'Last Updated',
    },
    placeholders: {
      name: 'Customer or shop name',
      phone: '+91 98765 43210',
      email: 'customer@example.com',
      addressLine1: 'Street address',
      addressLine2: 'Area or landmark',
      city: 'City',
      state: 'State',
      postalCode: 'Postal code',
      notes: 'Additional customer information',
    },
    create: {
      title: 'Add Customer',
      subtitle: 'Enter the customer’s contact information.',
      action: 'Create Customer',
      loading: 'Creating Customer…',
      success: 'Customer created successfully.',
    },
    edit: {
      title: 'Edit Customer',
      subtitle: 'Update this customer’s information.',
      action: 'Save Changes',
      loading: 'Saving Changes…',
      success: 'Customer updated successfully.',
    },
    details: {
      title: 'Customer Details',
      edit: 'Edit Customer',
      loadingTitle: 'Loading customer',
      loadingMessage: 'DistributorOS is retrieving this customer’s information.',
      errorTitle: 'Customer could not be loaded',
      errorMessage: 'Refresh the customer list and try opening this customer again.',
      active: 'Active',
    },
    archive: {
      action: 'Archive Customer',
      title: 'Archive this customer?',
      message: 'The customer will be hidden from active lists but can be restored later.',
      confirm: 'Archive Customer',
      loading: 'Archiving Customer…',
      success: 'Customer archived successfully.',
    },
    restore: {
      action: 'Restore Customer',
      title: 'Restore this customer?',
      message: 'The customer will return to active customer lists.',
      confirm: 'Restore Customer',
      loading: 'Restoring Customer…',
      success: 'Customer restored successfully.',
    },
    validation: {
      nameRequired: 'Customer name is required.',
      nameTooLong: 'Customer name must not exceed 160 characters.',
      duplicateName: 'A customer with this name already exists.',
      phoneInvalid: 'Please enter a valid phone number.',
      emailInvalid: 'Please enter a valid email address.',
      addressTooLong: 'Address lines must not exceed 200 characters.',
      cityTooLong: 'City must not exceed 100 characters.',
      stateTooLong: 'State must not exceed 100 characters.',
      postalCodeTooLong: 'Postal code must not exceed 20 characters.',
      notesTooLong: 'Notes must not exceed 2000 characters.',
    },
    errors: {
      duplicateName: 'A customer with this name already exists. Choose another name.',
      notFound: 'This customer was not found. Refresh the customer list and try again.',
      invalidPage: 'The customer list changed. Refresh it before loading more.',
      saveFailed: 'The customer could not be saved. Check the information and try again.',
      stateChangeFailed: 'The customer status could not be changed. Please try again.',
    },
  },
  products: {
    list: {
      title: 'Products',
      subtitle: 'Manage the products offered by this business.',
      create: 'Add Product',
      searchLabel: 'Search products',
      searchPlaceholder: 'Name, code, SKU, barcode, or category',
      filterLabel: 'Product status',
      sortLabel: 'Sort products',
      loadingTitle: 'Loading products',
      loadingMessage: 'DistributorOS is retrieving your product list.',
      errorTitle: 'Products could not be loaded',
      errorMessage: 'Check your connection and try loading the product list again.',
      emptyTitle: 'No products yet',
      emptyMessage: 'Add your first product to begin managing product information.',
      noResultsTitle: 'No matching products',
      noResultsMessage: 'Try a different product name, code, SKU, barcode, or category.',
      noArchivedTitle: 'No archived products',
      noArchivedMessage: 'Products you archive will appear here.',
      loadingMore: 'Loading more products…',
      updating: 'Updating product results…',
      archivedBadge: 'Archived',
    },
    filters: {
      all: 'All Products',
      active: 'Active',
      archived: 'Archived',
    },
    sorts: {
      newest: 'Newest',
      oldest: 'Oldest',
      nameAsc: 'Name A–Z',
      nameDesc: 'Name Z–A',
      priceAsc: 'Price Low → High',
      priceDesc: 'Price High → Low',
    },
    fields: {
      name: 'Product Name',
      productCode: 'Product Code',
      sku: 'SKU',
      barcode: 'Barcode',
      category: 'Category',
      description: 'Description',
      sellingPrice: 'Selling Price',
      unit: 'Unit',
      lowStockThreshold: 'Low Stock Threshold',
      status: 'Status',
    },
    placeholders: {
      name: 'Product name',
      sku: 'Optional SKU',
      barcode: 'Optional barcode',
      category: 'Product category',
      description: 'Product description',
      sellingPrice: '0.00',
      lowStockThreshold: '0',
    },
    units: {
      piece: 'Piece',
      kg: 'Kg',
      gram: 'Gram',
      litre: 'Litre',
      millilitre: 'Millilitre',
      box: 'Box',
      packet: 'Packet',
      dozen: 'Dozen',
    },
    create: {
      title: 'Add Product',
      subtitle: 'Enter the product’s pricing and identification details.',
      action: 'Create Product',
      loading: 'Creating Product…',
      success: 'Product created successfully.',
    },
    edit: {
      title: 'Edit Product',
      subtitle: 'Update this product’s information.',
      action: 'Save Changes',
      loading: 'Saving Changes…',
      success: 'Product updated successfully.',
    },
    details: {
      title: 'Product Details',
      edit: 'Edit Product',
      loadingTitle: 'Loading product',
      loadingMessage: 'DistributorOS is retrieving this product’s information.',
      errorTitle: 'Product could not be loaded',
      errorMessage: 'Refresh the product list and try opening this product again.',
      active: 'Active',
    },
    archive: {
      action: 'Archive Product',
      title: 'Archive this product?',
      message: 'The product will be hidden from active lists but can be restored later.',
      confirm: 'Archive Product',
      loading: 'Archiving Product…',
      success: 'Product archived successfully.',
    },
    restore: {
      action: 'Restore Product',
      title: 'Restore this product?',
      message: 'The product will return to active product lists.',
      confirm: 'Restore Product',
      loading: 'Restoring Product…',
      success: 'Product restored successfully.',
    },
    validation: {
      nameRequired: 'Product name is required.',
      nameTooLong: 'Product name must not exceed 160 characters.',
      duplicateName: 'A product with this name already exists.',
      skuTooLong: 'SKU must not exceed 100 characters.',
      duplicateSku: 'This SKU already exists.',
      barcodeTooLong: 'Barcode must not exceed 128 characters.',
      duplicateBarcode: 'Barcode already exists.',
      categoryTooLong: 'Category must not exceed 100 characters.',
      descriptionTooLong: 'Description must not exceed 2000 characters.',
      sellingPriceRequired: 'Selling price is required.',
      sellingPriceInvalid: 'Enter a valid selling price.',
      sellingPriceNegative: 'Selling price cannot be negative.',
      sellingPricePrecision: 'Selling price can have at most 2 decimal places.',
      sellingPriceTooLarge: 'Selling price is too large. Enter a smaller value.',
      unitRequired: 'Unit is required.',
      unitInvalid: 'Choose a supported product unit.',
      unitLocked: 'Unit cannot be changed after inventory has been recorded.',
      thresholdRequired: 'Low stock threshold is required.',
      thresholdInvalid: 'Enter a valid low stock threshold.',
      thresholdNegative: 'Low stock threshold cannot be negative.',
      thresholdPrecision: 'Low stock threshold can have at most 3 decimal places.',
      thresholdTooLarge: 'Low stock threshold is too large. Enter a smaller value.',
    },
    errors: {
      duplicateName: 'A product with this name already exists. Choose another name.',
      duplicateSku: 'This SKU already belongs to another product.',
      duplicateBarcode: 'This barcode already belongs to another product.',
      notFound: 'This product was not found. Refresh the product list and try again.',
      invalidPage: 'The product list changed. Refresh it before loading more.',
      saveFailed: 'The product could not be saved. Check the information and try again.',
      stateChangeFailed: 'The product status could not be changed. Please try again.',
      unitLocked: 'Unit cannot be changed after inventory has been recorded. Create a new product if a different unit is required.',
    },
  },
  sales: {
    list: {
      title: 'Sales',
      subtitle: 'Create drafts, post stock deductions, and review sales.',
      create: 'New Sale',
      searchLabel: 'Search sales',
      searchPlaceholder: 'Sale number or customer name',
      dateLabel: 'Sale date',
      datePlaceholder: 'YYYY-MM-DD',
      filterLabel: 'Sale status',
      sortLabel: 'Sort sales',
      loadingTitle: 'Loading sales',
      loadingMessage: 'DistributorOS is retrieving your sales.',
      errorTitle: 'Sales could not be loaded',
      errorMessage: 'Check your connection and try loading sales again.',
      emptyTitle: 'No sales yet',
      emptyMessage: 'Create your first sale draft to begin recording sales.',
      noResultsTitle: 'No matching sales',
      noResultsMessage: 'Try a different sale number, customer, status, or date.',
      loadingMore: 'Loading more sales…',
      updating: 'Updating sale results…',
      items: '{{count}} item',
      items_other: '{{count}} items',
    },
    filters: {
      all: 'All Sales',
      draft: 'Draft',
      posted: 'Posted',
      void: 'Void',
    },
    sorts: {
      newest: 'Newest',
      oldest: 'Oldest',
    },
    status: {
      draft: 'Draft',
      posted: 'Posted',
      void: 'Void',
    },
    form: {
      customer: 'Customer',
      customerSearchPlaceholder: 'Search active customers',
      selectedCustomer: 'Selected: {{name}}',
      noCustomers: 'No active customers match this search. Add or restore a customer first.',
      products: 'Add Products',
      productSearchPlaceholder: 'Search active products',
      noProducts: 'No active products match this search. Add or restore a product first.',
      saleItems: 'Sale Items',
      noItems: 'No products added. Search above and select a product.',
      subtotal: 'Subtotal',
      quantity: 'Quantity',
      unitPrice: 'Unit Price',
      remove: 'Remove',
      removeTitle: 'Remove this product?',
      removeMessage: 'This product and its entered quantity will be removed from the draft.',
      removeConfirm: 'Remove Product',
    },
    create: {
      title: 'New Sale',
      subtitle: 'Create an editable draft. Stock changes only when you post it.',
      action: 'Create Draft',
      loading: 'Creating Draft…',
      success: 'Sale draft created successfully.',
    },
    edit: {
      title: 'Edit Sale Draft',
      subtitle: 'Update the customer, products, quantities, or prices before posting.',
      action: 'Save Draft',
      loading: 'Saving Draft…',
      success: 'Sale draft updated successfully.',
    },
    details: {
      title: 'Sale Details',
      loadingTitle: 'Loading sale',
      loadingMessage: 'DistributorOS is retrieving this sale.',
      errorTitle: 'Sale could not be loaded',
      errorMessage: 'Refresh the sales list and try opening this sale again.',
      saleNumber: 'Sale Number',
      customer: 'Customer',
      status: 'Status',
      createdAt: 'Created',
      subtotal: 'Subtotal',
      items: 'Sale Items',
      quantity: 'Quantity',
      unitPrice: 'Unit Price',
      lineTotal: 'Line Total',
      edit: 'Edit Draft',
      postedNotice: 'This sale is posted and cannot be edited. Inventory has been deducted.',
      voidNotice: 'This sale is void. Its inventory deduction has been reversed.',
    },
    post: {
      action: 'Post Sale',
      title: 'Post this sale?',
      message: 'Posting permanently locks the sale and deducts its quantities from inventory.',
      confirm: 'Post Sale',
      loading: 'Posting Sale…',
      success: 'Sale posted successfully. Inventory and customer balance were updated.',
    },
    void: {
      action: 'Void Sale',
      title: 'Void this posted sale?',
      message: 'Voiding is permanent and will restore the sale quantities to inventory.',
      confirm: 'Void Sale',
      loading: 'Voiding Sale…',
      success: 'Sale voided successfully. Inventory was restored and the receivable was reversed.',
    },
    validation: {
      customerRequired: 'Select a customer for this sale.',
      itemsRequired: 'Add at least one product to this sale.',
      itemsTooMany: 'A sale can contain at most 100 products.',
      duplicateProduct: 'Each product can appear only once in a sale.',
      quantityRequired: 'Quantity is required.',
      quantityInvalid: 'Enter a valid quantity.',
      quantityPositive: 'Quantity must be greater than zero.',
      quantityPrecision: 'Quantity can have at most 3 decimal places.',
      quantityTooLarge: 'Quantity is too large. Enter a smaller value.',
      priceRequired: 'Unit price is required.',
      priceInvalid: 'Enter a valid unit price.',
      pricePositive: 'Unit price must be greater than zero.',
      pricePrecision: 'Unit price can have at most 2 decimal places.',
      priceTooLarge: 'Unit price is too large. Enter a smaller value.',
      dateInvalid: 'Enter the sale date as YYYY-MM-DD.',
    },
    errors: {
      notFound: 'This sale was not found. Refresh the sales list and try again.',
      notEditable: 'Only draft sales can be edited. Refresh this sale to see its current status.',
      alreadyPosted: 'This sale has already been posted and cannot be posted again.',
      alreadyVoided: 'This sale has already been voided and cannot be changed again.',
      notPosted: 'Only a posted sale can be voided.',
      hasIssuedInvoice: 'This sale has an issued invoice. Void the invoice instead so inventory and ledger records stay consistent.',
      customerArchived: 'The selected customer is archived. Restore the customer or choose another.',
      customerNotFound: 'The selected customer was not found. Choose another customer.',
      productArchived: 'A selected product is archived. Restore it or remove it from the sale.',
      productNotFound: 'A selected product was not found. Remove it and choose another product.',
      duplicateProduct: 'Each product can appear only once. Remove the duplicate product.',
      insufficientStock: 'There is not enough stock to post this sale. Reduce the highlighted quantity or receive stock first.',
      warehouseUnavailable: 'The default warehouse is unavailable. Restore it before posting sales.',
      invalidPage: 'The sales list changed. Refresh it before loading more.',
      submissionConflict: 'This submission changed while it was retried. Review the sale and try again.',
      editConflict: 'This draft changed in another tab or session. Reload it, review the latest changes, and try again.',
      inventoryHistoryMissing: 'This sale cannot be voided because its inventory history is incomplete. Contact support.',
      inventoryProjectionMissing: 'This sale cannot be voided because an inventory balance is missing. Run inventory reconciliation before trying again.',
      ledgerCorrupt: 'This sale cannot be changed because its customer ledger is inconsistent. Run ledger reconciliation before trying again.',
      customerPicker: 'Customers could not be loaded. Check your connection and try again.',
      productPicker: 'Products could not be loaded. Check your connection and try again.',
      saveFailed: 'The sale could not be saved. Check the highlighted information and try again.',
      loadFailed: 'The sale could not be loaded. Check your connection and try again.',
      lifecycleFailed: 'The sale status could not be changed. Refresh the sale and try again.',
    },
  },
  invoices: {
    list: {
      title: 'Invoices',
      subtitle: 'Create, issue, and review customer invoices.',
      create: 'New Invoice',
      searchLabel: 'Search invoices',
      searchPlaceholder: 'Invoice number, sale number, or customer',
      dateLabel: 'Invoice date',
      datePlaceholder: 'YYYY-MM-DD',
      filterLabel: 'Invoice status',
      sortLabel: 'Sort invoices',
      loadingTitle: 'Loading invoices',
      loadingMessage: 'DistributorOS is retrieving your invoices.',
      errorTitle: 'Invoices could not be loaded',
      emptyTitle: 'No invoices yet',
      emptyMessage: 'Create an invoice from a posted sale to begin issuing customer documents.',
      noResultsTitle: 'No matching invoices',
      noResultsMessage: 'Try a different invoice number, customer, sale number, status, or date.',
      loadingMore: 'Loading more invoices...',
      updating: 'Updating invoice results...',
      outstanding: 'Outstanding: {{amount}}',
    },
    filters: {
      all: 'All Invoices',
    },
    sorts: {
      newest: 'Newest',
      oldest: 'Oldest',
    },
    status: {
      draft: 'Draft',
      issued: 'Issued',
      void: 'Void',
    },
    create: {
      title: 'New Invoice',
      subtitle: 'Choose a posted sale. The invoice will preserve customer and product snapshots.',
      selectSale: 'Select Posted Sale',
      searchLabel: 'Search posted sales',
      searchPlaceholder: 'Sale number or customer name',
      loadingSales: 'Loading posted sales...',
      emptyTitle: 'No posted sales available',
      emptyMessage: 'Post a sale first, then return here to create its invoice.',
      loading: 'Creating Invoice...',
      success: 'Invoice created successfully.',
    },
    details: {
      title: 'Invoice Details',
      loadingTitle: 'Loading invoice',
      loadingMessage: 'DistributorOS is retrieving this invoice.',
      errorTitle: 'Invoice could not be loaded',
      status: 'Status',
      saleNumber: 'Sale Number',
      issueDate: 'Issue Date',
      createdAt: 'Created',
      currency: 'Currency',
      customer: 'Customer Snapshot',
      customerName: 'Customer Name',
      customerPhone: 'Customer Phone',
      customerAddress: 'Customer Address',
      noPhone: 'No phone number',
      noAddress: 'No address',
      items: 'Invoice Items',
      quantity: 'Quantity',
      unitPrice: 'Unit Price',
      lineTotal: 'Line Total',
      totals: 'Payment Summary',
      subtotal: 'Subtotal',
      taxTotal: 'Tax Total',
      grandTotal: 'Grand Total',
      allocatedAmount: 'Allocated Amount',
      outstandingAmount: 'Outstanding Balance',
      draftNotice: 'This invoice is a draft. Issue it only after confirming the customer document is correct.',
      voidNotice: 'This invoice is void. Reversal records have been created for the original sale.',
    },
    issue: {
      action: 'Issue Invoice',
      title: 'Issue this invoice?',
      message: 'Issuing locks the invoice snapshots permanently and applies available customer credit.',
      confirm: 'Issue Invoice',
      loading: 'Issuing Invoice...',
      success: 'Invoice issued successfully. Available customer credit was applied if possible.',
    },
    void: {
      action: 'Void Invoice',
      title: 'Void this invoice?',
      message: 'Voiding is permanent and creates reversal records for the linked sale.',
      confirm: 'Void Invoice',
      loading: 'Voiding Invoice...',
      success: 'Invoice voided successfully. The linked sale was reversed.',
    },
    pdf: {
      preview: 'Preview PDF',
      previewLoading: 'Opening PDF...',
      previewSuccess: 'Invoice PDF opened successfully.',
      share: 'Download or Share PDF',
      shareLoading: 'Preparing PDF...',
      shareSuccess: 'Invoice PDF is ready to share or download.',
      shareMessage: 'Invoice {{invoiceNumber}} from DistributorOS.',
    },
    customerHistory: {
      title: 'Customer Invoices',
      subtitle: 'Invoice history',
      viewInvoices: 'View Customer Invoices',
      loadingTitle: 'Loading customer invoices',
      loadingMessage: 'DistributorOS is retrieving this customer invoice history.',
      errorTitle: 'Customer invoices could not be loaded',
      updating: 'Updating customer invoice history...',
      emptyTitle: 'No invoices for this customer',
      emptyMessage: 'Issued and draft invoices for this customer will appear here.',
    },
    validation: {
      dateInvalid: 'Enter the invoice date as YYYY-MM-DD.',
    },
    errors: {
      notFound: 'This invoice was not found. Refresh the invoice list and try again.',
      alreadyExists: 'This sale already has an invoice. Open the existing invoice for this sale.',
      alreadyIssued: 'This invoice has already been issued and cannot be issued again.',
      alreadyVoided: 'This invoice has already been voided and cannot be changed again.',
      notIssued: 'Only an issued invoice can be voided.',
      saleNotFound: 'The selected sale was not found. Choose another posted sale.',
      saleNotPosted: 'Only posted sales can be invoiced. Post the sale before creating an invoice.',
      customerArchived: 'The sale customer is archived. Restore the customer before issuing an invoice.',
      itemsRequired: 'The selected sale has no items. Choose a posted sale with at least one item.',
      invalidPage: 'The invoice list changed. Refresh it before loading more.',
      submissionConflict: 'This invoice submission changed while it was retried. Review the invoice and try again.',
      corruptState: 'This invoice cannot be changed because its linked sale or ledger entry is inconsistent. Run reconciliation before trying again.',
      saveFailed: 'The invoice could not be saved. Check the selected sale and try again.',
      loadFailed: 'Invoices could not be loaded. Check your connection and try again.',
      lifecycleFailed: 'The invoice status could not be changed. Refresh the invoice and try again.',
      pdfFailed: 'The invoice PDF could not be prepared. Check your connection and try again.',
    },
  },
  payments: {
    list: {
      title: 'Payments',
      subtitle: 'Record customer collections and view immutable payment history.',
      create: 'Record Payment',
      searchLabel: 'Search payments',
      searchPlaceholder: 'Payment number, customer, or reference',
      dateLabel: 'Payment date',
      datePlaceholder: 'YYYY-MM-DD',
      filterLabel: 'Payment status',
      methodLabel: 'Payment method',
      sortLabel: 'Sort payments',
      loadingTitle: 'Loading payments',
      loadingMessage: 'DistributorOS is retrieving customer payments.',
      errorTitle: 'Payments could not be loaded',
      errorMessage: 'Check your connection and try loading payments again.',
      emptyTitle: 'No payments yet',
      emptyMessage: 'Record the first customer payment to begin tracking collections.',
      noResultsTitle: 'No matching payments',
      noResultsMessage: 'Try a different payment number, customer, reference, date, status, or method.',
      loadingMore: 'Loading more payments...',
      updating: 'Updating payment results...',
    },
    filters: {
      all: 'All Payments',
    },
    status: {
      posted: 'Posted',
      void: 'Void',
    },
    methods: {
      all: 'All Methods',
      cash: 'Cash',
      upi: 'UPI',
      bankTransfer: 'Bank Transfer',
      cheque: 'Cheque',
      other: 'Other',
    },
    sorts: {
      newest: 'Newest',
      oldest: 'Oldest',
    },
    form: {
      customer: 'Customer',
      customerSearchPlaceholder: 'Search active customers',
      selectedCustomer: 'Selected: {{name}}',
      noCustomers: 'No active customers match this search. Add or restore a customer first.',
      paymentDate: 'Payment Date',
      datePlaceholder: 'YYYY-MM-DD',
      amount: 'Amount',
      amountPlaceholder: '0.00',
      paymentMethod: 'Payment Method',
      referenceNumber: 'Reference Number',
      referencePlaceholder: 'UPI reference, cheque number, or bank transaction ID',
      notes: 'Notes',
      notesPlaceholder: 'Optional payment notes',
      allocations: 'Payment Allocation',
      allocationsHelp: 'Optionally allocate this payment to issued invoices. Unallocated amounts become customer credit.',
      selectCustomerForAllocations: 'Select a customer to see issued invoices with an outstanding balance.',
      loadingInvoices: 'Loading open invoices...',
      noInvoices: 'This customer has no issued invoices waiting for allocation.',
      allocateToReference: 'Allocate to {{reference}}',
      removeAllocation: 'Remove',
      allocatedAmount: 'Allocated Amount',
      allocationTotal: 'Allocation Total',
    },
    create: {
      title: 'Record Payment',
      subtitle: 'Post a customer collection and update receivables immediately.',
      action: 'Post Payment',
      loading: 'Posting Payment...',
      success: 'Payment posted successfully. Customer balance was updated.',
    },
    details: {
      title: 'Payment Details',
      loadingTitle: 'Loading payment',
      loadingMessage: 'DistributorOS is retrieving this payment.',
      errorTitle: 'Payment could not be loaded',
      errorMessage: 'Refresh the payment list and try opening this payment again.',
      customer: 'Customer',
      status: 'Status',
      paymentDate: 'Payment Date',
      createdAt: 'Created',
      amount: 'Amount',
      method: 'Method',
      referenceNumber: 'Reference Number',
      noReference: 'No reference number',
      notes: 'Notes',
      noNotes: 'No notes',
      allocatedAmount: 'Allocated Amount',
      unallocatedAmount: 'Unallocated Credit',
      allocations: 'Allocations',
      noAllocations: 'This payment was not allocated to a specific invoice. It is available as customer credit.',
      invoiceAllocation: 'Invoice',
      voidNotice: 'This payment is void. Its receivable credit has been reversed.',
    },
    void: {
      action: 'Void Payment',
      title: 'Void this payment?',
      message: 'Voiding is permanent and will reverse this customer payment in the ledger.',
      confirm: 'Void Payment',
      loading: 'Voiding Payment...',
      success: 'Payment voided successfully. Customer balance was updated.',
    },
    customerHistory: {
      title: 'Customer Payments',
      subtitle: 'Payment history',
      viewPayments: 'View Customer Payments',
      loadingTitle: 'Loading customer payments',
      loadingMessage: 'DistributorOS is retrieving this customer payment history.',
      errorTitle: 'Customer payments could not be loaded',
      loadingBalance: 'Loading customer balance...',
      updating: 'Updating customer payment history...',
      emptyTitle: 'No payments for this customer',
      emptyMessage: 'Posted payments for this customer will appear here.',
    },
    validation: {
      customerRequired: 'Select a customer for this payment.',
      dateRequired: 'Payment date is required.',
      dateInvalid: 'Enter the payment date as YYYY-MM-DD.',
      amountRequired: 'Payment amount is required.',
      amountInvalid: 'Enter a valid payment amount.',
      amountPositive: 'Payment amount must be greater than zero.',
      amountPrecision: 'Payment amount can have at most 2 decimal places.',
      amountTooLarge: 'Payment amount is too large. Enter a smaller value.',
      methodRequired: 'Select a payment method.',
      referenceTooLong: 'Reference number can contain at most 120 characters.',
      notesTooLong: 'Notes can contain at most 1000 characters.',
      allocationAmountRequired: 'Allocated amount is required.',
      allocationAmountInvalid: 'Enter a valid allocated amount.',
      allocationAmountPositive: 'Allocated amount must be greater than zero.',
      allocationAmountPrecision: 'Allocated amount can have at most 2 decimal places.',
      allocationTotalTooLarge: 'Allocated total cannot be greater than the payment amount.',
      duplicateAllocation: 'Each invoice can be allocated only once.',
    },
    errors: {
      notFound: 'This payment was not found. Refresh the payment list and try again.',
      alreadyVoided: 'This payment has already been voided and cannot be changed again.',
      customerArchived: 'The selected customer is archived. Restore the customer or choose another.',
      customerNotFound: 'The selected customer was not found. Choose another customer.',
      invalidAllocation: 'One or more allocation amounts are invalid. Review the highlighted allocations and try again.',
      duplicateAllocation: 'Each sale can receive only one allocation from this payment.',
      allocationTargetNotFound: 'An allocation target was not found for this customer. Refresh the payment form and try again.',
      invalidPage: 'The payments list changed. Refresh it before loading more.',
      submissionConflict: 'This payment submission changed while it was retried. Review the payment and try again.',
      ledgerCorrupt: 'This payment cannot be changed because its customer ledger is inconsistent. Run ledger reconciliation before trying again.',
      customerPicker: 'Customers could not be loaded. Check your connection and try again.',
      invoicePicker: 'Open invoices could not be loaded. Check your connection and try again.',
      saveFailed: 'The payment could not be saved. Check the highlighted information and try again.',
      loadFailed: 'Payments could not be loaded. Check your connection and try again.',
      lifecycleFailed: 'The payment status could not be changed. Refresh the payment and try again.',
    },
  },
  ledger: {
    summary: {
      title: 'Financial Summary',
      outstandingBalance: 'Outstanding Balance',
      availableCredit: 'Available Credit',
      totalSales: 'Total Sales',
      totalPayments: 'Total Payments',
      lastSaleDate: 'Last Sale Date',
      lastPaymentDate: 'Last Payment Date',
      noSales: 'No posted sales yet',
      noPayments: 'No posted payments yet',
      viewLedger: 'View Customer Ledger',
      loading: 'Loading financial summary…',
      error: 'The financial summary could not be loaded.',
    },
    list: {
      title: 'Customer Ledger',
      subtitle: 'Immutable receivable entries, newest first.',
      searchLabel: 'Search ledger references',
      searchPlaceholder: 'Sale or payment number',
      dateLabel: 'Ledger date',
      datePlaceholder: 'YYYY-MM-DD',
      typeLabel: 'Entry type',
      loadingTitle: 'Loading customer ledger',
      loadingMessage: 'DistributorOS is calculating this customer’s ledger.',
      errorTitle: 'Customer ledger could not be loaded',
      errorMessage: 'Check your connection and try loading the customer ledger again.',
      emptyTitle: 'No ledger entries yet',
      emptyMessage: 'Posted sales, payments, and reversals will appear here.',
      noResultsTitle: 'No matching ledger entries',
      noResultsMessage: 'Try a different sale or payment reference, date, or entry type.',
      loadingMore: 'Loading more ledger entries…',
      updating: 'Updating ledger results…',
    },
    filters: {
      all: 'All Entries',
      sale: 'Sales',
      reversal: 'Reversals',
      payment: 'Payments',
      paymentReversal: 'Payment Reversals',
    },
    entryTypes: {
      sale: 'Sale',
      reversal: 'Reversal',
      payment: 'Payment',
      paymentReversal: 'Payment Reversal',
    },
    fields: {
      date: 'Date',
      type: 'Type',
      reference: 'Reference',
      debit: 'Debit',
      credit: 'Credit',
      runningBalance: 'Running Balance',
      remarks: 'Remarks',
      noRemarks: 'No remarks',
      openReference: 'Open {{reference}}',
    },
    validation: {
      dateInvalid: 'Enter the ledger date as YYYY-MM-DD.',
    },
    errors: {
      corruptState: 'The customer ledger is inconsistent. Run ledger reconciliation before trying again.',
      invalidPage: 'The ledger changed. Refresh it before loading more.',
      loadFailed: 'The customer ledger could not be loaded. Check your connection and try again.',
    },
  },
  inventory: {
    list: {
      title: 'Inventory',
      subtitle: 'Current stock in the main warehouse.',
      history: 'View History',
      searchLabel: 'Search inventory',
      searchPlaceholder: 'Product name, code, SKU, or barcode',
      loadingTitle: 'Loading inventory',
      loadingMessage: 'DistributorOS is calculating current stock.',
      errorTitle: 'Inventory could not be loaded',
      errorMessage: 'Check your connection and try loading inventory again.',
      emptyTitle: 'No products in inventory',
      emptyMessage: 'Add a product first, then return here to record its stock.',
      noResultsTitle: 'No matching stock',
      noResultsMessage: 'Try a different product name, code, SKU, or barcode.',
      loadingMore: 'Loading more stock…',
      updating: 'Updating stock results…',
      available: 'Available',
    },
    details: {
      title: 'Current Stock',
      loadingTitle: 'Loading current stock',
      loadingMessage: 'DistributorOS is retrieving this product’s stock.',
      errorTitle: 'Stock could not be loaded',
      errorMessage: 'Refresh inventory and try opening this product again.',
      product: 'Product',
      productCode: 'Product Code',
      warehouse: 'Warehouse',
      availableQuantity: 'Available Quantity',
      lowStockThreshold: 'Low Stock Threshold',
      stockStatus: 'Stock Status',
      lastUpdated: 'Last Updated',
      noMovements: 'No stock movements recorded',
      operationsTitle: 'Record Stock Movement',
      history: 'View Product History',
      createdSuccess: 'Inventory movement recorded successfully.',
    },
    status: {
      outOfStock: 'Out of Stock',
      lowStock: 'Low Stock',
      normal: 'Normal',
    },
    operations: {
      openingRecorded: 'Opening Stock Recorded',
      openingRecordedHelp: 'Opening stock is recorded only once. Use a stock adjustment for corrections.',
      opening: 'Add Opening Stock',
      receipt: 'Receive Stock',
      adjustment: 'Adjust Stock',
      customerReturn: 'Record Customer Return',
      damage: 'Record Damage',
      spoilage: 'Record Spoilage',
      openingTitle: 'Opening Stock',
      receiptTitle: 'Stock Receipt',
      adjustmentTitle: 'Stock Adjustment',
      customerReturnTitle: 'Customer Return',
      damageTitle: 'Damaged Stock',
      spoilageTitle: 'Spoiled Stock',
      openingSubtitle: 'Record the product’s initial stock once.',
      receiptSubtitle: 'Add stock received into the warehouse.',
      adjustmentSubtitle: 'Correct stock with a positive or negative quantity.',
      customerReturnSubtitle: 'Add a standalone customer return to stock.',
      damageSubtitle: 'Remove damaged quantity from available stock.',
      spoilageSubtitle: 'Remove spoiled quantity from available stock.',
      quantity: 'Quantity',
      quantityPlaceholder: '0.000',
      remarks: 'Remarks',
      remarksPlaceholder: 'Optional details about this movement',
      reason: 'Reason',
      reasonPlaceholder: 'Explain why this adjustment is required',
      currentStock: 'Current stock',
      submit: 'Review Movement',
      loading: 'Recording Movement…',
      confirmTitle: 'Post this stock movement?',
      confirmMessage: 'Posted inventory movements are permanent and cannot be edited or deleted.',
      confirm: 'Post Movement',
      success: 'Stock movement recorded successfully.',
    },
    movementTypes: {
      openingStock: 'Opening Stock',
      stockReceipt: 'Stock Receipt',
      stockAdjustment: 'Stock Adjustment',
      customerReturn: 'Customer Return',
      damaged: 'Damaged',
      spoilage: 'Spoilage',
      sale: 'Sale',
      saleVoid: 'Sale Void',
    },
    history: {
      title: 'Inventory History',
      subtitle: 'Immutable stock movements, newest first.',
      searchLabel: 'Search inventory history',
      searchPlaceholder: 'Product name or code',
      loadingTitle: 'Loading inventory history',
      loadingMessage: 'DistributorOS is retrieving stock movements.',
      errorTitle: 'History could not be loaded',
      errorMessage: 'Check your connection and try loading history again.',
      emptyTitle: 'No stock movements yet',
      emptyMessage: 'Posted opening stock, receipts, adjustments, returns, damage, and spoilage will appear here.',
      noResultsTitle: 'No matching movements',
      noResultsMessage: 'Try a different product name or code.',
      loadingMore: 'Loading more movements…',
      updating: 'Updating movement results…',
      reference: 'Reference',
      remarks: 'Remarks',
      user: 'Recorded By',
      noReference: 'No reference',
      noRemarks: 'No remarks',
    },
    validation: {
      quantityRequired: 'Quantity is required.',
      quantityInvalid: 'Enter a valid quantity.',
      quantityPositive: 'Quantity must be greater than zero.',
      quantityZero: 'Quantity must not be zero.',
      quantityPrecision: 'Quantity can have at most 3 decimal places.',
      quantityTooLarge: 'Quantity is too large. Enter a smaller value.',
      reasonRequired: 'Reason is required for a stock adjustment.',
      remarksTooLong: 'Remarks must not exceed 1000 characters.',
    },
    errors: {
      productArchived: 'This product is archived. Restore it before recording stock.',
      warehouseArchived: 'The selected warehouse is archived. Select an active warehouse.',
      warehouseNotFound: 'This warehouse was not found. Refresh inventory and try again.',
      insufficientStock: 'This operation would reduce stock below zero. Enter a smaller quantity.',
      openingExists: 'Opening stock already exists. Use a stock adjustment to correct it.',
      invalidPage: 'The inventory list changed. Refresh it before loading more.',
      submissionConflict: 'This submission changed while it was being retried. Review it and submit again.',
      submissionFailed: 'The inventory movement could not be recorded. Check the information and try again.',
    },
  },
  insights: {
    dashboard: {
      loadingTitle: 'Loading dashboard',
      loadingMessage: 'DistributorOS is calculating your business snapshot.',
      errorTitle: 'Dashboard could not be loaded',
      subtitle: '{{business}} · Business date {{date}}',
      globalSearch: 'Global Search',
      reports: 'Reports',
      recentSales: 'Recent Sales',
      recentPayments: 'Recent Payments',
      recentInvoices: 'Recent Invoices',
      recentInventory: 'Recent Inventory Activity',
      topSellingProducts: 'Top Selling Products',
      highestOutstandingCustomers: 'Highest Outstanding Customers',
      emptyRecentSales: 'No sales have been recorded yet.',
      emptyRecentPayments: 'No payments have been recorded yet.',
      emptyRecentInvoices: 'No invoices have been recorded yet.',
      emptyRecentInventory: 'No inventory activity has been recorded yet.',
      emptyTopSellingProducts: 'Posted sales will appear here once products are sold.',
      emptyOutstandingCustomers: 'No customers currently have outstanding balances.',
    },
    metrics: {
      todaySales: "Today's Sales",
      todayCollections: "Today's Collections",
      outstandingReceivables: 'Outstanding Receivables',
      customerCredit: 'Customer Credit',
      totalCustomers: 'Total Customers',
      activeProducts: 'Active Products',
      inventoryValue: 'Inventory Value',
      lowStockProducts: 'Low Stock Products',
      outOfStockProducts: 'Out of Stock Products',
    },
    search: {
      title: 'Global Search',
      subtitle: 'Find customers, products, sales, invoices, payments, and inventory.',
      label: 'Search across DistributorOS',
      placeholder: 'Name, code, sale, invoice, or payment number',
      loading: 'Searching...',
      startTitle: 'Search your business',
      startMessage: 'Enter at least one character to search tenant-scoped business records.',
      emptyTitle: 'No matching records',
      emptyMessage: 'Try a different customer, product, invoice, sale, payment, or stock reference.',
      noGroupResults: 'No matches in this group.',
      groups: {
        customers: 'Customers',
        products: 'Products',
        sales: 'Sales',
        invoices: 'Invoices',
        payments: 'Payments',
        inventory: 'Inventory',
      },
    },
    reports: {
      title: 'Reports',
      subtitle: 'Read-only business reports with filters, sorting, pagination, and CSV export.',
      readOnlyTitle: 'Reports are read-only summaries',
      readOnlyMessage: 'Reports summarize existing records only. They never create, edit, or post business data.',
      open: 'Open',
      invalidTitle: 'Report not found',
      invalidMessage: 'Choose one of the available reports and try again.',
      loadingTitle: 'Loading report',
      loadingMessage: 'DistributorOS is preparing this report.',
      errorTitle: 'Report could not be loaded',
      emptyTitle: 'No report data yet',
      emptyMessage: 'Records from existing modules will appear here once available.',
      noResultsTitle: 'No matching report rows',
      noResultsMessage: 'Try a different search term, period, status, or sort option.',
      loadingMore: 'Loading more report rows...',
      updating: 'Updating report...',
      exportCsv: 'Export CSV',
      exportingCsv: 'Exporting CSV...',
      csvDownloaded: '{{file}} was downloaded.',
      csvSaved: 'CSV saved to {{path}}.',
      csvShared: '{{file}} is ready to share.',
      searchLabel: 'Search report',
      searchPlaceholder: 'Customer, product, code, or reference',
      periodLabel: 'Report period',
      dateFromLabel: 'Start date',
      dateToLabel: 'End date',
      datePlaceholder: 'YYYY-MM-DD',
      statusLabel: 'Status',
      sortLabel: 'Sort',
      types: {
        sales: {
          title: 'Sales Report',
          subtitle: 'Review sales by period, status, customer, amount, and sale number.',
        },
        payments: {
          title: 'Payments Report',
          subtitle: 'Review collections, allocations, unallocated credit, and payment status.',
        },
        outstanding: {
          title: 'Outstanding Customers',
          subtitle: 'Review customers with receivable balances and available credit.',
        },
        inventory: {
          title: 'Inventory Report',
          subtitle: 'Review current stock, selling price, inventory value, and stock status.',
        },
        lowStock: {
          title: 'Low Stock Report',
          subtitle: 'Review products that are low on stock or out of stock.',
        },
      },
      periods: {
        all: 'All Time',
        today: 'Today',
        yesterday: 'Yesterday',
        thisWeek: 'This Week',
        thisMonth: 'This Month',
        custom: 'Custom Range',
      },
      status: {
        all: 'All Statuses',
        draft: 'Draft',
        posted: 'Posted',
        issued: 'Issued',
        void: 'Void',
      },
      sorts: {
        newest: 'Newest',
        oldest: 'Oldest',
        amountDesc: 'Amount High to Low',
        amountAsc: 'Amount Low to High',
        customerAsc: 'Customer A-Z',
        customerDesc: 'Customer Z-A',
        highestOutstanding: 'Highest Outstanding',
        alphabetical: 'Alphabetical',
        nameAsc: 'Name A-Z',
        nameDesc: 'Name Z-A',
        stockAsc: 'Stock Low to High',
        stockDesc: 'Stock High to Low',
        valueAsc: 'Value Low to High',
        valueDesc: 'Value High to Low',
        lowestStock: 'Lowest Stock',
      },
      fields: {
        items: 'Items',
        allocated: 'Allocated',
        unallocated: 'Unallocated',
        credit: 'Credit',
        lastSale: 'Last sale',
        lastPayment: 'Last payment',
        price: 'Price',
      },
      stockStatus: {
        ok: 'Normal',
        low: 'Low Stock',
        out: 'Out of Stock',
      },
      validation: {
        customDatesRequired: 'Choose both a start date and an end date for a custom report.',
        dateInvalid: 'Enter dates as YYYY-MM-DD.',
        dateOrder: 'Start date must be before or equal to end date.',
      },
    },
    errors: {
      searchRequired: 'Enter a search term before searching.',
      filterInvalid: 'The selected report filter is invalid. Review the filters and try again.',
      invalidCursor: 'The report changed while loading more rows. Refresh the report and try again.',
      loadDashboard: 'The dashboard could not be loaded. Check your connection and try again.',
      loadSearch: 'Search could not be completed. Check your connection and try again.',
      loadReport: 'The report could not be loaded. Check your filters and try again.',
      exportCsv: 'The CSV file could not be exported. Check your connection and try again.',
    },
  },
} as const;
