import { en } from './en';

type Resource = Record<string, unknown>;

function mergeResources(base: Resource, overrides: Resource): Resource {
  const merged: Resource = { ...base };
  for (const [key, value] of Object.entries(overrides)) {
    if (!(key in base)) continue;
    const original = base[key];
    merged[key] =
      value &&
      original &&
      typeof value === 'object' &&
      typeof original === 'object' &&
      !Array.isArray(value) &&
      !Array.isArray(original)
        ? mergeResources(original as Resource, value as Resource)
        : value;
  }
  return merged;
}

const overrides = {
  common: {
    back: 'തിരികെ',
    cancel: 'റദ്ദാക്കുക',
    close: 'അടയ്ക്കുക',
    retry: 'വീണ്ടും ശ്രമിക്കുക',
    loading: 'ലോഡ് ചെയ്യുന്നു',
    save: 'സംരക്ഷിക്കുക',
    saving: 'സംരക്ഷിക്കുന്നു…',
  },
  brand: {
    name: 'DistributorOS',
    tagline: 'സങ്കീർണ്ണതകളില്ലാത്ത വിതരണ മാനേജ്മെന്റ്.',
  },
  startup: {
    loadingTitle: 'സെഷൻ പരിശോധിക്കുന്നു',
    loadingMessage: 'നിങ്ങളുടെ അക്കൗണ്ട് സുരക്ഷിതമായി പുനഃസ്ഥാപിക്കുന്നു.',
    errorTitle: 'സെഷൻ പരിശോധിക്കാനായില്ല',
    errorMessage: 'സെർവറുമായി ബന്ധപ്പെടാനായില്ല. കണക്ഷൻ പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക.',
  },
  login: {
    title: 'വീണ്ടും സ്വാഗതം',
    subtitle: 'നിങ്ങളുടെ ബിസിനസിലേക്ക് തുടരാൻ സൈൻ ഇൻ ചെയ്യുക.',
    emailLabel: 'ഇമെയിൽ',
    emailPlaceholder: 'owner@example.com',
    passwordLabel: 'പാസ്‌വേഡ്',
    passwordPlaceholder: 'പാസ്‌വേഡ് നൽകുക',
    action: 'സൈൻ ഇൻ',
    loading: 'സൈൻ ഇൻ ചെയ്യുന്നു…',
    noAccount: 'DistributorOS-ൽ പുതുതാണോ?',
    createAccount: 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    forgotPassword: 'പാസ്‌വേഡ് മറന്നോ?',
    passwordChanged: 'നിങ്ങളുടെ പാസ്‌വേഡ് മാറ്റി. പുതിയ പാസ്‌വേഡ് ഉപയോഗിച്ച് സൈൻ ഇൻ ചെയ്യുക.',
  },
  password: {
    forgotTitle: 'പാസ്‌വേഡ് പുനഃസജ്ജമാക്കുക',
    forgotSubtitle: 'അക്കൗണ്ട് ഇമെയിൽ നൽകുക. സുരക്ഷിതമായ പുനഃസജ്ജീകരണ ലിങ്ക് അയയ്ക്കും.',
    forgotAction: 'ലിങ്ക് അയയ്ക്കുക',
    forgotLoading: 'ലിങ്ക് അയയ്ക്കുന്നു…',
    forgotSuccess: 'ആ ഇമെയിലിന് അക്കൗണ്ട് ഉണ്ടെങ്കിൽ പാസ്‌വേഡ് പുനഃസജ്ജീകരണ ലിങ്ക് ഉടൻ അയയ്ക്കും.',
    backToLogin: 'സൈൻ ഇന്നിലേക്ക് മടങ്ങുക',
    resetTitle: 'പുതിയ പാസ്‌വേഡ് തിരഞ്ഞെടുക്കുക',
    resetSubtitle: 'കുറഞ്ഞത് 8 അക്ഷരങ്ങൾ ഉപയോഗിക്കുക. പൂർത്തിയാക്കുമ്പോൾ നിലവിലെ സെഷനുകൾ അവസാനിക്കും.',
    newPassword: 'പുതിയ പാസ്‌വേഡ്',
    confirmPassword: 'പുതിയ പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
    currentPassword: 'നിലവിലെ പാസ്‌വേഡ്',
    resetAction: 'പാസ്‌വേഡ് പുനഃസജ്ജമാക്കുക',
    resetLoading: 'പാസ്‌വേഡ് പുനഃസജ്ജമാക്കുന്നു…',
    changeTitle: 'പാസ്‌വേഡ് മാറ്റുക',
    changeSubtitle: 'പാസ്‌വേഡ് മാറ്റുമ്പോൾ എല്ലാ സജീവ സെഷനുകളിൽ നിന്നും സുരക്ഷിതമായി സൈൻ ഔട്ട് ചെയ്യും.',
    changeAction: 'പാസ്‌വേഡ് മാറ്റുക',
    changeLoading: 'പാസ്‌വേഡ് മാറ്റുന്നു…',
  },
  signup: {
    title: 'ബിസിനസ് അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    subtitle: 'നിങ്ങളുടെ ബിസിനസിനായി സുരക്ഷിതമായ അടിത്തറ ഒരുക്കുക.',
    businessNameLabel: 'ബിസിനസ് പേര്',
    businessNamePlaceholder: 'നിങ്ങളുടെ ബിസിനസ് പേര്',
    emailLabel: 'ഇമെയിൽ',
    passwordLabel: 'പാസ്‌വേഡ്',
    passwordPlaceholder: 'കുറഞ്ഞത് 8 അക്ഷരങ്ങൾ',
    action: 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    loading: 'അക്കൗണ്ട് സൃഷ്ടിക്കുന്നു…',
    hasAccount: 'ഇതിനകം അക്കൗണ്ടുണ്ടോ?',
    signIn: 'സൈൻ ഇൻ ചെയ്യുക',
  },
  validation: {
    businessNameRequired: 'ബിസിനസ് പേര് ആവശ്യമാണ്.',
    businessNameTooLong: 'ബിസിനസ് പേര് 120 അക്ഷരത്തിൽ കവിയരുത്.',
    emailRequired: 'ഇമെയിൽ ആവശ്യമാണ്.',
    emailInvalid: 'സാധുവായ ഇമെയിൽ നൽകുക.',
    passwordRequired: 'പാസ്‌വേഡ് ആവശ്യമാണ്.',
    passwordTooShort: 'പാസ്‌വേഡിൽ കുറഞ്ഞത് 8 അക്ഷരങ്ങൾ വേണം.',
    passwordTooLong: 'പാസ്‌വേഡ് 128 അക്ഷരത്തിൽ കവിയരുത്.',
    passwordsDoNotMatch: 'പാസ്‌വേഡുകൾ പൊരുത്തപ്പെടുന്നില്ല. രണ്ട് ഫീൽഡുകളിലും ഒരേ പാസ്‌വേഡ് നൽകുക.',
    currentPasswordIncorrect: 'നിലവിലെ പാസ്‌വേഡ് തെറ്റാണ്. പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക.',
  },
  errors: {
    currencyChangeRestricted: 'സാമ്പത്തിക ഇടപാടുകൾ നിലവിലുണ്ടെങ്കിൽ കറൻസി മാറ്റാനാകില്ല. ചരിത്ര തുകകൾ സംരക്ഷിക്കാൻ നിലവിലെ കറൻസി നിലനിർത്തുക.',
    rateLimited: 'വളരെയധികം ശ്രമങ്ങൾ നടന്നു. കുറച്ച് നേരം കാത്ത് വീണ്ടും ശ്രമിക്കുക.',
    passwordResetInvalid: 'ഈ പാസ്‌വേഡ് പുനഃസജ്ജീകരണ ലിങ്ക് അസാധുവാണ് അല്ലെങ്കിൽ കാലഹരണപ്പെട്ടു. പുതിയ ലിങ്ക് അഭ്യർത്ഥിക്കുക.',
    currentPasswordIncorrect: 'നിലവിലെ പാസ്‌വേഡ് തെറ്റാണ്. പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക.',
    passwordUnchanged: 'നിലവിലെ പാസ്‌വേഡിൽ നിന്ന് വ്യത്യസ്തമായ പുതിയ പാസ്‌വേഡ് തിരഞ്ഞെടുക്കുക.',
    emailRegistered: 'ഈ ഇമെയിൽ ഇതിനകം രജിസ്റ്റർ ചെയ്തിട്ടുണ്ട്. സൈൻ ഇൻ ചെയ്യുക അല്ലെങ്കിൽ മറ്റൊരു ഇമെയിൽ ഉപയോഗിക്കുക.',
    invalidCredentials: 'ഇമെയിൽ അല്ലെങ്കിൽ പാസ്‌വേഡ് തെറ്റാണ്. വിവരങ്ങൾ പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക.',
    sessionExpired: 'നിങ്ങളുടെ സെഷൻ കാലഹരണപ്പെട്ടു. വീണ്ടും സൈൻ ഇൻ ചെയ്യുക.',
    businessAccess: 'ഈ ബിസിനസുമായി നിങ്ങളുടെ അക്കൗണ്ട് ബന്ധിപ്പിച്ചിട്ടില്ല. സഹായത്തിനായി പിന്തുണയെ സമീപിക്കുക.',
    forbidden: 'ഈ പ്രവർത്തനം നടത്താൻ അനുമതിയില്ല.',
    notFound: 'ആവശ്യപ്പെട്ട വിവരം കണ്ടെത്താനായില്ല. പുതുക്കി വീണ്ടും ശ്രമിക്കുക.',
    network: 'സെർവറുമായി ബന്ധപ്പെടാനായില്ല. ഫ്രീ സർവർ ആരംഭിക്കുകയാണെങ്കിൽ കുറച്ച് സമയത്തിന് ശേഷം വീണ്ടും ശ്രമിക്കുക.',
    server: 'സെർവറിന് അഭ്യർത്ഥന പൂർത്തിയാക്കാനായില്ല. വീണ്ടും ശ്രമിക്കുക.',
    validation: 'അടയാളപ്പെടുത്തിയ വിവരങ്ങൾ പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക.',
    unknown: 'ഈ പ്രവർത്തനം പൂർത്തിയാക്കാനായില്ല. വീണ്ടും ശ്രമിക്കുക.',
  },
  home: {
    signOut: 'സൈൻ ഔട്ട്',
    manageCustomers: 'ഉപഭോക്താക്കൾ',
    manageProducts: 'ഉൽപ്പന്നങ്ങൾ',
    manageInventory: 'സ്റ്റോക്ക്',
    manageSales: 'വിൽപ്പന',
    managePayments: 'പേയ്മെന്റുകൾ',
    manageInvoices: 'ഇൻവോയ്സുകൾ',
    businessSettings: 'ബിസിനസ് ക്രമീകരണങ്ങൾ',
    quickActions: 'ദ്രുത പ്രവർത്തനങ്ങൾ',
    modules: {
      customers: {
        title: 'ഉപഭോക്താക്കൾ',
        description: 'ഉപഭോക്തൃ വിവരങ്ങൾ ചേർത്ത് നിയന്ത്രിക്കുക.',
      },
      products: {
        title: 'ഉൽപ്പന്നങ്ങൾ',
        description: 'ഉൽപ്പന്നങ്ങൾ, യൂണിറ്റുകൾ, വിലകൾ നിയന്ത്രിക്കുക.',
      },
      inventory: {
        title: 'സ്റ്റോക്ക്',
        description: 'സ്റ്റോക്ക് പരിശോധിച്ച് നീക്കങ്ങൾ രേഖപ്പെടുത്തുക.',
      },
      sales: {
        title: 'വിൽപ്പന',
        description: 'വിൽപ്പന സൃഷ്ടിച്ച് പരിശോധിച്ച് പോസ്റ്റ് ചെയ്യുക.',
      },
      payments: {
        title: 'പേയ്മെന്റുകൾ',
        description: 'ഉപഭോക്തൃ പിരിവുകൾ രേഖപ്പെടുത്തി പിന്തുടരുക.',
      },
      invoices: {
        title: 'ഇൻവോയ്സുകൾ',
        description: 'ഉപഭോക്തൃ ഇൻവോയ്സുകൾ സൃഷ്ടിച്ച് പങ്കിടുക.',
      },
    },
  },
  navigation: {
    home: 'ഹോം',
    sales: 'വിൽപ്പന',
    customers: 'ഉപഭോക്താക്കൾ',
    products: 'ഉൽപ്പന്നങ്ങൾ',
    more: 'കൂടുതൽ',
  },
  more: {
    title: 'കൂടുതൽ',
    subtitle: 'കൂടുതൽ ബിസിനസ് ഉപകരണങ്ങളും ആപ്പ് ക്രമീകരണങ്ങളും.',
    items: {
      inventory: {
        title: 'സ്റ്റോക്ക്',
        subtitle: 'സ്റ്റോക്ക് ബാലൻസ്, ചരിത്രം, നീക്കങ്ങൾ പരിശോധിക്കുക.',
      },
      payments: {
        title: 'പേയ്മെന്റുകൾ',
        subtitle: 'പിരിവുകൾ രേഖപ്പെടുത്തി പേയ്മെന്റ് ചരിത്രം പരിശോധിക്കുക.',
      },
      invoices: {
        title: 'ഇൻവോയ്സുകൾ',
        subtitle: 'ഇൻവോയ്സുകൾ സൃഷ്ടിച്ച് ഇഷ്യൂ ചെയ്ത് പങ്കിടുക.',
      },
      reports: {
        title: 'റിപ്പോർട്ടുകൾ',
        subtitle: 'വായനയ്ക്ക് മാത്രമുള്ള റിപ്പോർട്ടുകളും എക്സ്പോർട്ടുകളും തുറക്കുക.',
      },
      search: {
        title: 'തിരയൽ',
        subtitle: 'എല്ലാ ബിസിനസ് വിഭാഗങ്ങളിലുമുള്ള രേഖകൾ കണ്ടെത്തുക.',
      },
      settings: {
        title: 'ക്രമീകരണങ്ങൾ',
        subtitle: 'ബിസിനസ്, രൂപം, ഭാഷ, അക്കൗണ്ട് ക്രമീകരണങ്ങൾ നിയന്ത്രിക്കുക.',
      },
    },
  },
  settings: {
    timezone: 'ബിസിനസ് സമയമേഖല',
    timezonePlaceholder: 'Asia/Kolkata',
    timezoneHelp: 'Asia/Kolkata പോലുള്ള IANA സമയമേഖല ഉപയോഗിക്കുക. തീയതികൾ, റിപ്പോർട്ടുകൾ, എക്സ്പോർട്ടുകൾ എന്നിവ ഇത് ഉപയോഗിക്കും.',
    open: 'ക്രമീകരണങ്ങൾ',
    openHint: 'ബിസിനസ്, രൂപം, ഭാഷ, അക്കൗണ്ട് ക്രമീകരണങ്ങൾ തുറക്കുക.',
    title: 'ക്രമീകരണങ്ങൾ',
    subtitle: 'നിങ്ങളുടെ ബിസിനസും ആപ്പ് അനുഭവവും നിയന്ത്രിക്കുക.',
    businessSection: 'ബിസിനസ്',
    businessDescription: 'ബിസിനസ് വിവരങ്ങളും പുതിയ രേഖകൾക്കുള്ള കറൻസിയും.',
    businessName: 'ബിസിനസ് പേര്',
    businessNamePlaceholder: 'നിങ്ങളുടെ ബിസിനസ് പേര്',
    currency: 'കറൻസി',
    currencyHelp: 'പുതിയ സാമ്പത്തിക രേഖകൾ ഈ കറൻസി ഉപയോഗിക്കും. പഴയ ഇൻവോയ്സുകൾക്ക് അവയുടെ യഥാർത്ഥ കറൻസി തുടരും.',
    appearanceSection: 'രൂപഭാവം',
    appearanceDescription: 'ഈ ഉപകരണത്തിൽ DistributorOS എങ്ങനെ കാണണമെന്ന് തിരഞ്ഞെടുക്കുക.',
    language: 'ഭാഷ',
    languageSection: 'ഭാഷ',
    languageHelp: 'ഭാഷാമാറ്റം ഉടൻ തന്നെ ആപ്പിലാകെ പ്രയോഗിക്കും.',
    english: 'ഇംഗ്ലീഷ്',
    malayalam: 'മലയാളം',
    theme: 'തീം',
    themeHelp: 'ലൈറ്റ്, ഡാർക്ക്, അല്ലെങ്കിൽ ഉപകരണത്തിന്റെ തീം ഉപയോഗിക്കുക.',
    light: 'ലൈറ്റ്',
    dark: 'ഡാർക്ക്',
    system: 'സിസ്റ്റം',
    themeOptions: {
      light: 'എപ്പോഴും ലൈറ്റ് നിറവിന്യാസം ഉപയോഗിക്കുക.',
      dark: 'എപ്പോഴും ഡാർക്ക് നിറവിന്യാസം ഉപയോഗിക്കുക.',
      system: 'ഈ ഉപകരണത്തിന്റെ രൂപഭാവ ക്രമീകരണം പിന്തുടരുക.',
    },
    languageOptions: {
      en: 'DistributorOS ഇംഗ്ലീഷിൽ കാണിക്കുക.',
      ml: 'DistributorOS മലയാളത്തിൽ കാണിക്കുക.',
    },
    accountSection: 'അക്കൗണ്ട്',
    accountDescription: 'നിങ്ങൾ സൈൻ ഇൻ ചെയ്ത വിവരങ്ങളും ബിസിനസ് അംഗത്വവും.',
    accountEmail: 'ഇമെയിൽ',
    accountBusiness: 'ബിസിനസ് പേര്',
    changePassword: 'പാസ്‌വേഡ് മാറ്റുക',
    changePasswordHint: 'പാസ്‌വേഡ് പുതുക്കി മറ്റ് സെഷനുകളിൽ നിന്ന് സൈൻ ഔട്ട് ചെയ്യുക.',
    save: 'ക്രമീകരണങ്ങൾ സംരക്ഷിക്കുക',
    saving: 'ക്രമീകരണങ്ങൾ സംരക്ഷിക്കുന്നു…',
    success: 'ബിസിനസ് ക്രമീകരണങ്ങൾ വിജയകരമായി പുതുക്കി.',
    errorTitle: 'ക്രമീകരണങ്ങൾ സംരക്ഷിക്കാനായില്ല',
    loadError: 'ക്രമീകരണങ്ങൾ ലോഡ് ചെയ്യാനായില്ല. കണക്ഷൻ പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക.',
    validation: {
      timezoneRequired: 'ബിസിനസ് സമയമേഖല ആവശ്യമാണ്.',
      timezoneInvalid: 'Asia/Kolkata പോലുള്ള സാധുവായ സമയമേഖല നൽകുക.',
      businessNameRequired: 'ബിസിനസ് പേര് ആവശ്യമാണ്.',
      businessNameTooLong: 'ബിസിനസ് പേര് 120 അക്ഷരത്തിൽ കവിയരുത്.',
    },
  },
  logout: {
    title: 'DistributorOS-ൽ നിന്ന് സൈൻ ഔട്ട് ചെയ്യണോ?',
    message: 'സൈൻ ഔട്ട് ചെയ്യണമെന്ന് ഉറപ്പാണോ?',
    confirm: 'സൈൻ ഔട്ട്',
    confirmAccessibilityLabel: 'സൈൻ ഔട്ട് സ്ഥിരീകരിക്കുക',
    loading: 'സൈൻ ഔട്ട് ചെയ്യുന്നു…',
  },
  unsavedChanges: {
    title: 'സംരക്ഷിക്കാത്ത മാറ്റങ്ങൾ ഉപേക്ഷിക്കണോ?',
    message: 'നിങ്ങളുടെ മാറ്റങ്ങൾ സംരക്ഷിച്ചിട്ടില്ല. അവ ഉപേക്ഷിച്ച് ഈ സ്ക്രീനിൽ നിന്ന് പുറത്തുകടക്കണോ?',
    discard: 'മാറ്റങ്ങൾ ഉപേക്ഷിക്കുക',
    keepEditing: 'തിരുത്തൽ തുടരുക',
  },
  customers: {
    list: {
      title: 'ഉപഭോക്താക്കൾ',
      subtitle: 'ഈ ബിസിനസിലെ ഉപഭോക്തൃ വിവരങ്ങൾ നിയന്ത്രിക്കുക.',
      create: 'ഉപഭോക്താവിനെ ചേർക്കുക',
      searchLabel: 'ഉപഭോക്താക്കളെ തിരയുക',
      searchPlaceholder: 'പേര്, ഫോൺ, കോഡ്, അല്ലെങ്കിൽ ഇമെയിൽ',
      filterLabel: 'ഉപഭോക്തൃ നില',
      sortLabel: 'ക്രമീകരണം',
      loadingTitle: 'ഉപഭോക്താക്കളെ ലോഡ് ചെയ്യുന്നു',
      errorTitle: 'ഉപഭോക്താക്കളെ ലോഡ് ചെയ്യാനായില്ല',
      emptyTitle: 'ഉപഭോക്താക്കളില്ല',
      emptyMessage: 'ആദ്യ ഉപഭോക്താവിനെ ചേർത്ത് തുടങ്ങുക.',
      noResultsTitle: 'ചേരുന്ന ഉപഭോക്താക്കളില്ല',
      noArchivedTitle: 'ആർക്കൈവ് ചെയ്ത ഉപഭോക്താക്കളില്ല',
      archivedBadge: 'ആർക്കൈവ് ചെയ്തത്',
    },
    filters: { all: 'എല്ലാ ഉപഭോക്താക്കളും', active: 'സജീവം', archived: 'ആർക്കൈവ് ചെയ്തത്' },
    sorts: { newest: 'പുതിയത്', oldest: 'പഴയത്', nameAsc: 'പേര് A–Z', nameDesc: 'പേര് Z–A' },
    fields: {
      name: 'ഉപഭോക്താവിന്റെ പേര്', customerCode: 'ഉപഭോക്തൃ കോഡ്', phone: 'ഫോൺ', email: 'ഇമെയിൽ',
      addressLine1: 'വിലാസം 1', addressLine2: 'വിലാസം 2', city: 'നഗരം', state: 'സംസ്ഥാനം',
      postalCode: 'പിൻ കോഡ്', notes: 'കുറിപ്പുകൾ', status: 'നില', createdAt: 'സൃഷ്ടിച്ചത്', updatedAt: 'അവസാനം പുതുക്കിയത്',
    },
    create: { title: 'ഉപഭോക്താവിനെ ചേർക്കുക', action: 'ഉപഭോക്താവിനെ സൃഷ്ടിക്കുക', loading: 'സൃഷ്ടിക്കുന്നു…', success: 'ഉപഭോക്താവിനെ വിജയകരമായി സൃഷ്ടിച്ചു.' },
    edit: { title: 'ഉപഭോക്താവിനെ തിരുത്തുക', action: 'മാറ്റങ്ങൾ സംരക്ഷിക്കുക', loading: 'സംരക്ഷിക്കുന്നു…', success: 'ഉപഭോക്താവിനെ വിജയകരമായി പുതുക്കി.' },
    details: { title: 'ഉപഭോക്തൃ വിവരങ്ങൾ', edit: 'തിരുത്തുക', active: 'സജീവം' },
    archive: { action: 'ആർക്കൈവ് ചെയ്യുക', title: 'ഈ ഉപഭോക്താവിനെ ആർക്കൈവ് ചെയ്യണോ?', confirm: 'ആർക്കൈവ് ചെയ്യുക', success: 'ഉപഭോക്താവിനെ ആർക്കൈവ് ചെയ്തു.' },
    restore: { action: 'പുനഃസ്ഥാപിക്കുക', title: 'ഈ ഉപഭോക്താവിനെ പുനഃസ്ഥാപിക്കണോ?', confirm: 'പുനഃസ്ഥാപിക്കുക', success: 'ഉപഭോക്താവിനെ പുനഃസ്ഥാപിച്ചു.' },
    validation: { nameRequired: 'ഉപഭോക്താവിന്റെ പേര് ആവശ്യമാണ്.', duplicateName: 'ഈ പേരിലുള്ള ഉപഭോക്താവ് ഇതിനകം ഉണ്ട്.', phoneInvalid: 'സാധുവായ ഫോൺ നമ്പർ നൽകുക.', emailInvalid: 'സാധുവായ ഇമെയിൽ വിലാസം നൽകുക.' },
  },
  products: {
    list: {
      title: 'ഉൽപ്പന്നങ്ങൾ', subtitle: 'ഈ ബിസിനസിലെ ഉൽപ്പന്നങ്ങൾ നിയന്ത്രിക്കുക.', create: 'ഉൽപ്പന്നം ചേർക്കുക',
      searchLabel: 'ഉൽപ്പന്നങ്ങൾ തിരയുക', filterLabel: 'ഉൽപ്പന്ന നില', sortLabel: 'ക്രമീകരണം',
      loadingTitle: 'ഉൽപ്പന്നങ്ങൾ ലോഡ് ചെയ്യുന്നു', errorTitle: 'ഉൽപ്പന്നങ്ങൾ ലോഡ് ചെയ്യാനായില്ല',
      emptyTitle: 'ഉൽപ്പന്നങ്ങളില്ല', emptyMessage: 'ആദ്യ ഉൽപ്പന്നം ചേർത്ത് തുടങ്ങുക.', noResultsTitle: 'ചേരുന്ന ഉൽപ്പന്നങ്ങളില്ല', archivedBadge: 'ആർക്കൈവ് ചെയ്തത്',
    },
    filters: { all: 'എല്ലാ ഉൽപ്പന്നങ്ങളും', active: 'സജീവം', archived: 'ആർക്കൈവ് ചെയ്തത്' },
    sorts: { newest: 'പുതിയത്', oldest: 'പഴയത്', nameAsc: 'പേര് A–Z', nameDesc: 'പേര് Z–A', priceAsc: 'വില കുറവ് മുതൽ', priceDesc: 'വില കൂടുതൽ മുതൽ' },
    fields: { name: 'ഉൽപ്പന്നത്തിന്റെ പേര്', productCode: 'ഉൽപ്പന്ന കോഡ്', category: 'വിഭാഗം', description: 'വിവരണം', sellingPrice: 'വിൽപ്പന വില', unit: 'യൂണിറ്റ്', lowStockThreshold: 'കുറഞ്ഞ സ്റ്റോക്ക് പരിധി', status: 'നില' },
    create: { title: 'ഉൽപ്പന്നം ചേർക്കുക', action: 'ഉൽപ്പന്നം സൃഷ്ടിക്കുക', loading: 'സൃഷ്ടിക്കുന്നു…', success: 'ഉൽപ്പന്നം വിജയകരമായി സൃഷ്ടിച്ചു.' },
    edit: { title: 'ഉൽപ്പന്നം തിരുത്തുക', action: 'മാറ്റങ്ങൾ സംരക്ഷിക്കുക', loading: 'സംരക്ഷിക്കുന്നു…', success: 'ഉൽപ്പന്നം വിജയകരമായി പുതുക്കി.' },
    validation: { nameRequired: 'ഉൽപ്പന്നത്തിന്റെ പേര് ആവശ്യമാണ്.', sellingPriceRequired: 'വിൽപ്പന വില ആവശ്യമാണ്.', sellingPriceInvalid: 'സാധുവായ വില നൽകുക.', sellingPriceNegative: 'വിൽപ്പന വില നെഗറ്റീവ് ആകരുത്.', unitRequired: 'യൂണിറ്റ് തിരഞ്ഞെടുക്കുക.' },
  },
  inventory: {
    list: {
      title: 'സ്റ്റോക്ക്', subtitle: 'പ്രധാന വെയർഹൗസിലെ നിലവിലെ സ്റ്റോക്ക്.', history: 'ചരിത്രം കാണുക',
      searchLabel: 'സ്റ്റോക്ക് തിരയുക', loadingTitle: 'സ്റ്റോക്ക് ലോഡ് ചെയ്യുന്നു', errorTitle: 'സ്റ്റോക്ക് ലോഡ് ചെയ്യാനായില്ല',
      emptyTitle: 'സ്റ്റോക്കിൽ ഉൽപ്പന്നങ്ങളില്ല', noResultsTitle: 'ചേരുന്ന സ്റ്റോക്ക് ഇല്ല', available: 'ലഭ്യം',
    },
    details: { title: 'നിലവിലെ സ്റ്റോക്ക്', product: 'ഉൽപ്പന്നം', productCode: 'ഉൽപ്പന്ന കോഡ്', warehouse: 'വെയർഹൗസ്', availableQuantity: 'ലഭ്യമായ അളവ്', lowStockThreshold: 'കുറഞ്ഞ സ്റ്റോക്ക് പരിധി', stockStatus: 'സ്റ്റോക്ക് നില', lastUpdated: 'അവസാനം പുതുക്കിയത്' },
    status: { outOfStock: 'സ്റ്റോക്ക് തീർന്നു', lowStock: 'സ്റ്റോക്ക് കുറവ്', normal: 'സാധാരണ' },
    operations: { opening: 'ആരംഭ സ്റ്റോക്ക്', openingRecorded: 'ആരംഭ സ്റ്റോക്ക് രേഖപ്പെടുത്തി', openingRecordedHelp: 'ആരംഭ സ്റ്റോക്ക് ഒരിക്കൽ മാത്രം രേഖപ്പെടുത്താം. തിരുത്തലുകൾക്ക് സ്റ്റോക്ക് ക്രമീകരണം ഉപയോഗിക്കുക.', receipt: 'സ്റ്റോക്ക് സ്വീകരിക്കുക', adjustment: 'സ്റ്റോക്ക് തിരുത്തുക', customerReturn: 'ഉപഭോക്തൃ മടക്കം', damage: 'കേടായ സ്റ്റോക്ക്', spoilage: 'നശിച്ച സ്റ്റോക്ക്', quantity: 'അളവ്', remarks: 'കുറിപ്പുകൾ', reason: 'കാരണം', submit: 'പരിശോധിക്കുക', confirm: 'പോസ്റ്റ് ചെയ്യുക', success: 'സ്റ്റോക്ക് നീക്കം രേഖപ്പെടുത്തി.' },
    history: { title: 'സ്റ്റോക്ക് ചരിത്രം', searchLabel: 'ചരിത്രം തിരയുക', loadingTitle: 'ചരിത്രം ലോഡ് ചെയ്യുന്നു', errorTitle: 'ചരിത്രം ലോഡ് ചെയ്യാനായില്ല', emptyTitle: 'സ്റ്റോക്ക് നീക്കങ്ങളില്ല', reference: 'റഫറൻസ്', remarks: 'കുറിപ്പുകൾ', user: 'രേഖപ്പെടുത്തിയത്' },
    validation: { quantityRequired: 'അളവ് ആവശ്യമാണ്.', quantityInvalid: 'സാധുവായ അളവ് നൽകുക.', quantityPositive: 'അളവ് പൂജ്യത്തിൽ കൂടുതലായിരിക്കണം.', quantityZero: 'അളവ് പൂജ്യം ആകരുത്.', reasonRequired: 'സ്റ്റോക്ക് തിരുത്തലിന് കാരണം ആവശ്യമാണ്.' },
  },
  sales: {
    list: { title: 'വിൽപ്പന', create: 'വിൽപ്പന സൃഷ്ടിക്കുക', searchLabel: 'വിൽപ്പന തിരയുക', loadingTitle: 'വിൽപ്പന ലോഡ് ചെയ്യുന്നു', errorTitle: 'വിൽപ്പന ലോഡ് ചെയ്യാനായില്ല', emptyTitle: 'വിൽപ്പനകളില്ല', noResultsTitle: 'ചേരുന്ന വിൽപ്പനകളില്ല' },
    status: { draft: 'ഡ്രാഫ്റ്റ്', posted: 'പോസ്റ്റ് ചെയ്തത്', void: 'റദ്ദാക്കിയത്' },
    fields: { customer: 'ഉപഭോക്താവ്', date: 'തീയതി', product: 'ഉൽപ്പന്നം', quantity: 'അളവ്', unitPrice: 'യൂണിറ്റ് വില', lineTotal: 'ആകെ', subtotal: 'ഉപആകെ', total: 'ആകെ', status: 'നില' },
    create: { title: 'വിൽപ്പന സൃഷ്ടിക്കുക', action: 'ഡ്രാഫ്റ്റ് സംരക്ഷിക്കുക', loading: 'സംരക്ഷിക്കുന്നു…', success: 'വിൽപ്പന ഡ്രാഫ്റ്റ് സൃഷ്ടിച്ചു.' },
    details: { title: 'വിൽപ്പന വിവരങ്ങൾ', customer: 'ഉപഭോക്താവ്', items: 'ഇനങ്ങൾ', subtotal: 'ഉപആകെ', status: 'നില' },
    post: { action: 'വിൽപ്പന പോസ്റ്റ് ചെയ്യുക', title: 'ഈ വിൽപ്പന പോസ്റ്റ് ചെയ്യണോ?', confirm: 'പോസ്റ്റ് ചെയ്യുക', success: 'വിൽപ്പന വിജയകരമായി പോസ്റ്റ് ചെയ്തു.' },
    void: { action: 'വിൽപ്പന റദ്ദാക്കുക', title: 'ഈ വിൽപ്പന റദ്ദാക്കണോ?', confirm: 'റദ്ദാക്കുക', success: 'വിൽപ്പന റദ്ദാക്കി.' },
    validation: { customerRequired: 'ഉപഭോക്താവിനെ തിരഞ്ഞെടുക്കുക.', itemsRequired: 'കുറഞ്ഞത് ഒരു ഉൽപ്പന്നമെങ്കിലും ചേർക്കുക.', quantityRequired: 'അളവ് ആവശ്യമാണ്.', quantityPositive: 'അളവ് പൂജ്യത്തിൽ കൂടുതലായിരിക്കണം.', unitPriceRequired: 'യൂണിറ്റ് വില ആവശ്യമാണ്.' },
    errors: { editConflict: 'ഈ ഡ്രാഫ്റ്റ് മറ്റൊരു ടാബിലോ സെഷനിലോ മാറ്റിയിട്ടുണ്ട്. ഏറ്റവും പുതിയ മാറ്റങ്ങൾ വീണ്ടും ലോഡ് ചെയ്ത് പരിശോധിക്കുക.' },
  },
  payments: {
    list: { title: 'പേയ്മെന്റുകൾ', create: 'പേയ്മെന്റ് രേഖപ്പെടുത്തുക', searchLabel: 'പേയ്മെന്റുകൾ തിരയുക', loadingTitle: 'പേയ്മെന്റുകൾ ലോഡ് ചെയ്യുന്നു', errorTitle: 'പേയ്മെന്റുകൾ ലോഡ് ചെയ്യാനായില്ല', emptyTitle: 'പേയ്മെന്റുകളില്ല', noResultsTitle: 'ചേരുന്ന പേയ്മെന്റുകളില്ല' },
    status: { posted: 'പോസ്റ്റ് ചെയ്തത്', void: 'റദ്ദാക്കിയത്' },
    methods: { cash: 'പണം', upi: 'UPI', bankTransfer: 'ബാങ്ക് ട്രാൻസ്ഫർ', cheque: 'ചെക്ക്', other: 'മറ്റുള്ളവ' },
    fields: { customer: 'ഉപഭോക്താവ്', paymentDate: 'പേയ്മെന്റ് തീയതി', amount: 'തുക', method: 'രീതി', referenceNumber: 'റഫറൻസ് നമ്പർ', notes: 'കുറിപ്പുകൾ' },
    create: { title: 'പേയ്മെന്റ് രേഖപ്പെടുത്തുക', action: 'പേയ്മെന്റ് പോസ്റ്റ് ചെയ്യുക', loading: 'പോസ്റ്റ് ചെയ്യുന്നു…', success: 'പേയ്മെന്റ് വിജയകരമായി പോസ്റ്റ് ചെയ്തു.' },
    details: { title: 'പേയ്മെന്റ് വിവരങ്ങൾ', customer: 'ഉപഭോക്താവ്', status: 'നില', amount: 'തുക', method: 'രീതി', allocatedAmount: 'വകയിരുത്തിയ തുക', unallocatedAmount: 'വകയിരുത്താത്ത ക്രെഡിറ്റ്', allocations: 'വകയിരുത്തലുകൾ' },
    void: { action: 'പേയ്മെന്റ് റദ്ദാക്കുക', title: 'ഈ പേയ്മെന്റ് റദ്ദാക്കണോ?', confirm: 'റദ്ദാക്കുക', success: 'പേയ്മെന്റ് റദ്ദാക്കി.' },
    validation: { customerRequired: 'ഉപഭോക്താവിനെ തിരഞ്ഞെടുക്കുക.', dateRequired: 'പേയ്മെന്റ് തീയതി ആവശ്യമാണ്.', amountRequired: 'പേയ്മെന്റ് തുക ആവശ്യമാണ്.', amountInvalid: 'സാധുവായ തുക നൽകുക.', amountPositive: 'തുക പൂജ്യത്തിൽ കൂടുതലായിരിക്കണം.', methodRequired: 'പേയ്മെന്റ് രീതി തിരഞ്ഞെടുക്കുക.' },
  },
  invoices: {
    list: { title: 'ഇൻവോയ്സുകൾ', create: 'ഇൻവോയ്സ് സൃഷ്ടിക്കുക', searchLabel: 'ഇൻവോയ്സുകൾ തിരയുക', loadingTitle: 'ഇൻവോയ്സുകൾ ലോഡ് ചെയ്യുന്നു', errorTitle: 'ഇൻവോയ്സുകൾ ലോഡ് ചെയ്യാനായില്ല', emptyTitle: 'ഇൻവോയ്സുകളില്ല', noResultsTitle: 'ചേരുന്ന ഇൻവോയ്സുകളില്ല' },
    status: { draft: 'ഡ്രാഫ്റ്റ്', issued: 'നൽകിയത്', void: 'റദ്ദാക്കിയത്' },
    fields: { invoiceNumber: 'ഇൻവോയ്സ് നമ്പർ', saleNumber: 'വിൽപ്പന നമ്പർ', customer: 'ഉപഭോക്താവ്', issueDate: 'നൽകിയ തീയതി', status: 'നില', currency: 'കറൻസി', subtotal: 'ഉപആകെ', tax: 'നികുതി', grandTotal: 'ആകെ', outstanding: 'ബാക്കി' },
    create: { title: 'ഇൻവോയ്സ് സൃഷ്ടിക്കുക', action: 'ഡ്രാഫ്റ്റ് സൃഷ്ടിക്കുക', success: 'ഇൻവോയ്സ് ഡ്രാഫ്റ്റ് സൃഷ്ടിച്ചു.' },
    details: { title: 'ഇൻവോയ്സ് വിവരങ്ങൾ', items: 'ഇനങ്ങൾ', paymentSummary: 'പേയ്മെന്റ് സംഗ്രഹം', downloadPdf: 'PDF ഡൗൺലോഡ് ചെയ്യുക' },
    issue: { action: 'ഇൻവോയ്സ് നൽകുക', title: 'ഈ ഇൻവോയ്സ് നൽകണോ?', confirm: 'നൽകുക', success: 'ഇൻവോയ്സ് വിജയകരമായി നൽകി.' },
    void: { action: 'ഇൻവോയ്സ് റദ്ദാക്കുക', title: 'ഈ ഇൻവോയ്സ് റദ്ദാക്കണോ?', confirm: 'റദ്ദാക്കുക', success: 'ഇൻവോയ്സ് റദ്ദാക്കി.' },
  },
  ledger: {
    summary: { title: 'സാമ്പത്തിക സംഗ്രഹം', outstandingBalance: 'ബാക്കി തുക', availableCredit: 'ലഭ്യമായ ക്രെഡിറ്റ്', totalSales: 'ആകെ വിൽപ്പന', totalPayments: 'ആകെ പേയ്മെന്റുകൾ', viewLedger: 'ലെഡ്ജർ കാണുക', loading: 'സംഗ്രഹം ലോഡ് ചെയ്യുന്നു…' },
    list: { title: 'ഉപഭോക്തൃ ലെഡ്ജർ', searchLabel: 'ലെഡ്ജർ തിരയുക', loadingTitle: 'ലെഡ്ജർ ലോഡ് ചെയ്യുന്നു', errorTitle: 'ലെഡ്ജർ ലോഡ് ചെയ്യാനായില്ല', emptyTitle: 'ലെഡ്ജർ എൻട്രികളില്ല', noResultsTitle: 'ചേരുന്ന എൻട്രികളില്ല' },
    filters: { all: 'എല്ലാ എൻട്രികളും', sale: 'വിൽപ്പന', reversal: 'തിരിച്ചടികൾ', payment: 'പേയ്മെന്റുകൾ', paymentReversal: 'പേയ്മെന്റ് തിരിച്ചടികൾ' },
    fields: { date: 'തീയതി', type: 'തരം', reference: 'റഫറൻസ്', debit: 'ഡെബിറ്റ്', credit: 'ക്രെഡിറ്റ്', runningBalance: 'നിലവിലെ ബാലൻസ്', remarks: 'കുറിപ്പുകൾ', openReference: '{{reference}} തുറക്കുക' },
  },
  insights: {
    dashboard: {
      loadingTitle: 'ഡാഷ്ബോർഡ് ലോഡ് ചെയ്യുന്നു', errorTitle: 'ഡാഷ്ബോർഡ് ലോഡ് ചെയ്യാനായില്ല',
      subtitle: '{{business}} · ബിസിനസ് തീയതി {{date}}', globalSearch: 'ആഗോള തിരച്ചിൽ', reports: 'റിപ്പോർട്ടുകൾ',
      recentSales: 'സമീപകാല വിൽപ്പന', recentPayments: 'സമീപകാല പേയ്മെന്റുകൾ', recentInvoices: 'സമീപകാല ഇൻവോയ്സുകൾ',
      recentInventory: 'സമീപകാല സ്റ്റോക്ക് പ്രവർത്തനം', topSellingProducts: 'കൂടുതൽ വിറ്റ ഉൽപ്പന്നങ്ങൾ', highestOutstandingCustomers: 'കൂടുതൽ ബാക്കിയുള്ള ഉപഭോക്താക്കൾ',
      emptyRecentSales: 'ഇതുവരെ വിൽപ്പന രേഖപ്പെടുത്തിയിട്ടില്ല.', emptyRecentPayments: 'ഇതുവരെ പേയ്മെന്റ് രേഖപ്പെടുത്തിയിട്ടില്ല.', emptyRecentInvoices: 'ഇതുവരെ ഇൻവോയ്സ് രേഖപ്പെടുത്തിയിട്ടില്ല.', emptyRecentInventory: 'സ്റ്റോക്ക് പ്രവർത്തനങ്ങളില്ല.',
    },
    metrics: { todaySales: 'ഇന്നത്തെ വിൽപ്പന', todayCollections: 'ഇന്നത്തെ പിരിവ്', outstandingReceivables: 'ലഭിക്കാനുള്ള ബാക്കി', customerCredit: 'ഉപഭോക്തൃ ക്രെഡിറ്റ്', totalCustomers: 'ആകെ ഉപഭോക്താക്കൾ', activeProducts: 'സജീവ ഉൽപ്പന്നങ്ങൾ', inventoryValue: 'സ്റ്റോക്ക് മൂല്യം', lowStockProducts: 'സ്റ്റോക്ക് കുറവുള്ള ഉൽപ്പന്നങ്ങൾ', outOfStockProducts: 'സ്റ്റോക്ക് തീർന്ന ഉൽപ്പന്നങ്ങൾ' },
    search: { title: 'ആഗോള തിരച്ചിൽ', subtitle: 'ഉപഭോക്താക്കൾ, ഉൽപ്പന്നങ്ങൾ, വിൽപ്പന, ഇൻവോയ്സുകൾ, പേയ്മെന്റുകൾ, സ്റ്റോക്ക് എന്നിവ കണ്ടെത്തുക.', label: 'DistributorOS-ൽ തിരയുക', placeholder: 'പേര്, കോഡ്, വിൽപ്പന, ഇൻവോയ്സ്, അല്ലെങ്കിൽ പേയ്മെന്റ് നമ്പർ', loading: 'തിരയുന്നു…', startTitle: 'നിങ്ങളുടെ ബിസിനസ് തിരയുക', emptyTitle: 'ചേരുന്ന രേഖകളില്ല', groups: { customers: 'ഉപഭോക്താക്കൾ', products: 'ഉൽപ്പന്നങ്ങൾ', sales: 'വിൽപ്പന', invoices: 'ഇൻവോയ്സുകൾ', payments: 'പേയ്മെന്റുകൾ', inventory: 'സ്റ്റോക്ക്' } },
    reports: {
      title: 'റിപ്പോർട്ടുകൾ', subtitle: 'ഫിൽട്ടറുകളും CSV എക്സ്പോർട്ടുമുള്ള വായനാമാത്ര ബിസിനസ് റിപ്പോർട്ടുകൾ.', open: 'തുറക്കുക',
      loadingTitle: 'റിപ്പോർട്ട് തയ്യാറാക്കുന്നു', errorTitle: 'റിപ്പോർട്ട് ലോഡ് ചെയ്യാനായില്ല', emptyTitle: 'റിപ്പോർട്ട് ഡാറ്റയില്ല', noResultsTitle: 'ചേരുന്ന റിപ്പോർട്ട് വരികളില്ല',
      exportCsv: 'CSV എക്സ്പോർട്ട് ചെയ്യുക', exportingCsv: 'CSV എക്സ്പോർട്ട് ചെയ്യുന്നു…', searchLabel: 'റിപ്പോർട്ട് തിരയുക', periodLabel: 'കാലയളവ്', dateFromLabel: 'ആരംഭ തീയതി', dateToLabel: 'അവസാന തീയതി', statusLabel: 'നില', sortLabel: 'ക്രമീകരണം',
      periods: { all: 'എല്ലാ കാലവും', today: 'ഇന്ന്', yesterday: 'ഇന്നലെ', thisWeek: 'ഈ ആഴ്ച', thisMonth: 'ഈ മാസം', custom: 'ഇഷ്ടാനുസൃത കാലയളവ്' },
      status: { all: 'എല്ലാ നിലകളും', draft: 'ഡ്രാഫ്റ്റ്', posted: 'പോസ്റ്റ് ചെയ്തത്', issued: 'നൽകിയത്', void: 'റദ്ദാക്കിയത്' },
      fields: { items: 'ഇനങ്ങൾ', allocated: 'വകയിരുത്തിയത്', unallocated: 'വകയിരുത്താത്തത്', credit: 'ക്രെഡിറ്റ്', lastSale: 'അവസാന വിൽപ്പന', lastPayment: 'അവസാന പേയ്മെന്റ്', price: 'വില' },
      stockStatus: { ok: 'സാധാരണ', low: 'സ്റ്റോക്ക് കുറവ്', out: 'സ്റ്റോക്ക് തീർന്നു' },
    },
  },
} satisfies Resource;

export const ml = mergeResources(en as unknown as Resource, overrides) as typeof en;
